version: "3.8"

services:
  backend:
    image: backend-prd
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CERTS_PATH=/usr/src/app/certs
      - KEY_PATH=/run/secrets/key
      - APP_USER=appUser1
    secrets:
      - key
    networks:
      - fabric_test

secrets:
  key:
    external: true

networks:
  fabric_test:
    external: true
